# Generated by Django 4.2.1 on 2023-07-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('photoUrl', models.ImageField(blank=True, null=True, upload_to='photo_folder')),
                ('logoUrl', models.ImageField(blank=True, null=True, upload_to='logo_folder')),
                ('link', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('editeAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
