# Generated by Django 4.2.1 on 2023-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projetmodel_sponsorlogourl_alter_projetmodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetmodel',
            name='logoUrl',
            field=models.ImageField(blank=True, null=True, upload_to='logo_folder/'),
        ),
        migrations.AlterField(
            model_name='projetmodel',
            name='photoUrl',
            field=models.ImageField(blank=True, null=True, upload_to='photo_folder/'),
        ),
        migrations.AlterField(
            model_name='projetmodel',
            name='sponsorLogoUrl',
            field=models.ImageField(blank=True, null=True, upload_to='logo_sponsor/'),
        ),
    ]
