# Generated by Django 4.2.1 on 2023-05-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_uploadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='caption',
        ),
    ]
