# Generated by Django 4.2.1 on 2023-08-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_posttexte_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='author_id',
        ),
    ]
